'use strict';
(async()=>{
 const output=document.querySelector('#results'),frame=document.querySelector('#app');
 const dbName='daftar-isolated-test-'+Date.now();
 const lines=[];
 const delay=ms=>new Promise(r=>setTimeout(r,ms));
 function assert(ok,label){if(!ok)throw new Error(label);lines.push('PASS — '+label);console.log('PASS — '+label);output.textContent=lines.join('\n');}
 async function wait(fn){for(let i=0;i<100;i++){if(fn())return;await delay(60);}throw new Error('Timeout');}
 try{
 let html=await (await fetch('../index.html')).text();
 const base=new URL('../',location.href).href;
 const setup=`const nativeOpen=indexedDB.open.bind(indexedDB);indexedDB.open=(name,version)=>nativeOpen('${dbName}',version);`;
 html=html.replace('<head>',`<head><base href="${base}"><script>${setup}</script>`);
 frame.srcdoc=html;
 await wait(()=>frame.contentDocument.querySelector('.currency-card'));
 const w=frame.contentWindow,d=frame.contentDocument;
 assert(d.querySelectorAll('.currency-card').length===3,'Drie lege valutakaarten geladen');
 async function add(type,amount,code,title,date='2026-09-17'){
 w.openEntry(type);d.querySelector('#entry-title').value=title;if(type==='income')d.querySelector('#income-amount-'+code).value=amount;else{d.querySelector('#entry-amount').value=amount;d.querySelector('#entry-currency').value=code;}d.querySelector('#entry-date').value=date;
 d.querySelector('#entry-form').requestSubmit();await wait(()=>!d.querySelector('#entry-dialog').open);
 }
 await add('income','1250.25','USD','Test inkomen');
 await add('expense','150.10','USD','Test uitgave');
 await add('income','500','TRY','Test lira');
 await add('expense','10000','SYP','Test Syrisch');
 assert(w.eval('records.length')===4,'Vier transacties opgeslagen');
 assert(w.eval('totals(monthlyRecords(),"USD").balance')===1100.15,'Nauwkeurige maandbalans USD: 1100.15');
 assert(w.eval('totals(monthlyRecords(),"TRY").balance')===500,'TRY blijft onafhankelijk');
 assert(w.eval('totals(monthlyRecords(),"SYP").balance')===-10000,'SYP negatieve balans correct');
 const id=w.eval('records.find(r=>r.title==="Test inkomen").id');
 w.openEntry('income',id);d.querySelector('#income-amount-USD').value='1450.25';d.querySelector('#entry-form').requestSubmit();await wait(()=>!d.querySelector('#entry-dialog').open);
 assert(w.eval('totals(monthlyRecords(),"USD").balance')===1300.15,'Bewerken herberekent de balans');
 assert(w.eval('history.some(h=>h.before?.amount===1250.25)'),'Oud bedrag staat in de wijzigingsgeschiedenis');
 await add('income','900','USD','Andere maand','2026-08-01');
 assert(w.eval('totals(monthlyRecords("2026-09"),"USD").balance')===1300.15,'Maandfilter sluit andere maanden uit');
 w.eval('currentMonth="2026-09";currentRoute="expenses";render()');
 const canvas=document.createElement('canvas');canvas.width=2;canvas.height=2;canvas.getContext('2d').fillRect(0,0,2,2);
 const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));
 const photo=await w.readPhoto(new w.File([blob],'receipt.png',{type:'image/png'}));
 assert(w.validatePhoto(photo),'Afbeelding gelezen en gevalideerd');
 w.openEntry('expense');d.querySelector('#entry-title').value='Uitgave met foto';d.querySelector('#entry-amount').value='10';d.querySelector('#entry-date').value='2026-09-18';
 w._testPhoto=photo;w.eval('pendingPhotos=[window._testPhoto]');
 d.querySelector('#entry-form').requestSubmit();await wait(()=>!d.querySelector('#entry-dialog').open);
 assert(w.eval('records.find(r=>r.title==="Uitgave met foto").photos.length')===1,'Foto opgeslagen bij uitgave');
 const photoID=w.eval('records.find(r=>r.title==="Uitgave met foto").id');w.detail(photoID);
 await wait(()=>d.querySelector('.attachment-gallery img')?.complete);
 assert(d.querySelector('.attachment-gallery img').naturalWidth===2,'Opgeslagen foto wordt correct weergegeven');d.querySelector('#detail-dialog').close();
 w.eval('currentRoute="settings";render()');
 const identity=d.querySelector('#identity-form');identity.elements.name.value='دفتر الاختبار';identity.requestSubmit();await wait(()=>d.querySelector('#brand-name').textContent==='دفتر الاختبار');
 assert(w.eval('settings.name')==='دفتر الاختبار','Instellingen opgeslagen');
 const cat=d.querySelector('.category-form[data-type="expense"]');cat.elements.categoryName.value='تصنيف اختبار';cat.requestSubmit();await wait(()=>w.eval('settings.categories.expense.length')===5);
 assert(w.eval('settings.categories.expense.some(c=>c.name==="تصنيف اختبار")'),'Categorie toegevoegd');
 w.eval('download=(content,name,type)=>{window._download={content,name,type}}');
 await w.exportBackup();
 const backup=JSON.parse(w._download.content);
 assert(backup.records.length===6&&backup.records.some(r=>r.photos.length)&&backup.history.length>=8,'Back-up bevat transacties, foto’s, instellingen en geschiedenis');
 w.validateBackup(backup);
 assert(true,'Eigen back-up slaagt voor validatie');
 const bad=JSON.parse(JSON.stringify(backup));bad.records[0].amount=-5;let invalid=false;try{w.validateBackup(bad);}catch{invalid=true;}assert(invalid,'Ongeldige import wordt geweigerd');
 w.confirm=()=>true;
 await add('income','1','USD','Na back-up');
 const count=w.eval('records.length'),hist=w.eval('history.length');
 await w.importBackup(new w.File([JSON.stringify(backup)],'backup.json',{type:'application/json'}));
 assert(w.eval('records.length')===count,'Herstellen verwijdert geen nieuwere transacties');
 assert(w.eval('history.length')>hist,'Import bewaart vorige versies in geschiedenis');
 await w.refreshData();
 assert(w.eval('records.length')===7,'Gegevens opnieuw uit IndexedDB gelezen');
 w.eval('currentMonth="2026-09";currentRoute="reports";listSearch="foto";render()');
 assert(d.querySelectorAll('tbody tr').length===1,'Zoeken filtert transacties');
 w.exportCSV();assert(w._download.name==='daftar-report-2026-09.csv'&&w._download.content.includes('Uitgave met foto'),'CSV-export gebruikt zichtbare maand en zoekfilter');
 w.eval('currentRoute="history";render()');assert(d.querySelectorAll('.history-item').length>8,'Wijzigingsgeschiedenis wordt weergegeven');
 assert(!d.body.textContent.includes('[object Object]'),'Geen ruwe objecten in interface');
 // New regression coverage: multi-currency income, optional names, soft delete, CSV dates and theme.
 const before=w.eval('records.length');
 w.openEntry('income');
 assert(!d.querySelector('#entry-title').required&&d.querySelectorAll('[data-income-currency]').length===3,'Naam en drie valutavelden optioneel');
 d.querySelector('#entry-date').value='2026-09-03';
 d.querySelector('#entry-form').requestSubmit();await wait(()=>d.querySelector('#form-error').textContent.length>0);
 assert(w.eval('records.length')===before&&d.querySelector('#entry-dialog').open,'Volledig lege invoer geweigerd zonder gegevensverlies');
 d.querySelector('#income-amount-USD').value='12.35';d.querySelector('#income-amount-TRY').value='23.45';d.querySelector('#income-amount-SYP').value='456.78';
 d.querySelector('#entry-form').requestSubmit();await wait(()=>!d.querySelector('#entry-dialog').open);
 const unnamed=w.eval('records.filter(r=>r.title===""&&!r.deletedAt)');
 assert(unnamed.length===3&&new Set(unnamed.map(r=>r.batchId)).size===1,'Drie bedragen zonder naam atomair opgeslagen als één invoer');
 assert(unnamed.every(r=>r.date==='2026-09-03'),'Identieke kalenderdatum zonder tijdzoneverschuiving');
 const groupId=unnamed[0].id;
 w.openEntry('income',groupId);
 assert(d.querySelector('#income-amount-USD').value==='12.35'&&d.querySelector('#income-amount-SYP').value==='456.78','Bewerken toont alle bedragen van dezelfde invoer');
 d.querySelector('#income-amount-TRY').value='';d.querySelector('#income-amount-USD').value='20.10';
 d.querySelector('#entry-form').requestSubmit();await wait(()=>!d.querySelector('#entry-dialog').open);
 w._batch=unnamed[0].batchId;
 assert(w.eval('records.filter(r=>r.batchId===window._batch&&!r.deletedAt).length')===2,'Leegmaken van één bedrag verwijdert alleen die valuta');
 assert(w.eval('records.some(r=>r.batchId===window._batch&&r.currency==="TRY"&&r.deletedAt)'),'Verwijderd bedrag blijft herstelbaar opgeslagen');
 const active=w.eval('records.find(r=>r.batchId===window._batch&&!r.deletedAt).id');
 w.confirm=()=>false;await w.deleteRecord(active,true);
 assert(w.eval('records.filter(r=>r.batchId===window._batch&&!r.deletedAt).length')===2,'Annuleren van verwijderen bewaart de volledige invoer');
 w.confirm=()=>true;await w.deleteRecord(active,true);
 assert(w.eval('records.filter(r=>r.batchId===window._batch&&!r.deletedAt).length')===0,'Volledige invoer verwijderd met alle resterende valuta’s');
 assert(w.eval('monthlyRecords().every(r=>r.batchId!==window._batch)'),'Verwijderde bedragen uitgesloten van maandtotalen');
 await w.restoreRecord(active);
 assert(w.eval('records.filter(r=>r.batchId===window._batch&&!r.deletedAt).length')===1,'Eén verwijderd bedrag succesvol hersteld');
 await w.deleteRecord(photoID);
 assert(w.eval('records.find(r=>r.id==="'+photoID+'").photos.length')===1,'Verwijderen van uitgave bewaart foto en historie');
 w.eval('currentRoute="history";render()');
 assert(d.querySelectorAll('[data-restore]').length>=3,'Herstelknoppen zichtbaar bij verwijderde bedragen');
 await w.exportBackup();const newBackup=JSON.parse(w._download.content);w.validateBackup(newBackup);
 assert(newBackup.version===3&&newBackup.records.some(r=>r.deletedAt),'Nieuwe back-up bewaart groepsverband, lege namen en verwijderstatus');
 const legacy=JSON.parse(JSON.stringify(backup));legacy.version=1;w.validateBackup(legacy);assert(true,'Versie 1-back-ups blijven leesbaar');
 const deletedBefore=w.eval('records.filter(r=>r.deletedAt).length');
 await w.importBackup(new w.File([JSON.stringify(newBackup)],'new-backup.json',{type:'application/json'}));
 assert(w.eval('records.filter(r=>r.deletedAt).length')===deletedBefore,'Import bewaart verwijderstatus');
 w.eval('currentMonth="2026-09";currentRoute="reports";listSearch="";listCurrency="";listCategory="";render()');
 w.exportCSV();
 assert(w._download.content.includes('"=""2026-09-03"""'),'CSV-datum is vaste ISO-tekst voor spreadsheets');
 assert(!w._download.content.includes('Uitgave met foto'),'CSV bevat geen verwijderde uitgaven');
 const themeBefore=w.localStorage.getItem('daftar-theme');
 w.applyTheme('light');
 assert(w.getComputedStyle(d.querySelector('.primary')).backgroundColor==='rgb(43, 95, 179)'&&w.getComputedStyle(d.body).backgroundColor==='rgb(244, 247, 252)','ألوان المرجع الأزرق الملكي والخلفية الفاتحة مطبقة');
 const colorSheet=d.querySelector('link[href^="css/brand-colors.css"]').sheet;
 const geometry=()=>[...d.querySelectorAll('.sidebar,.topbar,.page-heading,.filter-toolbar,.currency-card,.panel,#view-content')].map(el=>{const r=el.getBoundingClientRect();return [r.x,r.y,r.width,r.height];});
 const afterColors=JSON.stringify(geometry());colorSheet.disabled=true;
 const beforeColors=JSON.stringify(geometry());colorSheet.disabled=false;
 assert(beforeColors===afterColors,'تغيير الألوان لا يغير أحجام العناصر أو مواقعها أو التخطيط');
 w.applyTheme('light');d.querySelector('#theme-toggle').click();
 assert(d.documentElement.dataset.theme==='dark'&&w.localStorage.getItem('daftar-theme')==='dark','Nachtmodus geactiveerd en lokaal onthouden');
 const panelColor=w.getComputedStyle(d.querySelector('.panel')).backgroundColor;
 assert(panelColor==='rgb(22, 31, 50)','Nachtmodus past echte paneelachtergrond aan');
 d.querySelector('#theme-toggle').click();assert(d.documentElement.dataset.theme==='light','Terugschakelen naar dagmodus werkt');
 assert(/^\d{2}\/\d{2}\/\d{4} · \d{2}:\d{2}:\d{2}$/.test(d.querySelector('#header-datetime').textContent),'Kop toont numerieke lokale datum en tijd');
 if(themeBefore===null)w.localStorage.removeItem('daftar-theme');else w.localStorage.setItem('daftar-theme',themeBefore);
 // Debt entries use their own store and must not alter cash accounting.
 w.eval('currentRoute="debts";render()');
 assert(d.querySelector('#debts-register')&&!d.querySelector('#add-debt').hidden&&d.querySelector('#filter-toolbar').hidden,'قسم الديون مستقل ويعرض زر الإضافة');
 const cashBefore=w.eval('JSON.stringify(["USD","TRY","SYP"].map(c=>totals(records,c)))');
 w.openDebt();await w.saveDebt({preventDefault(){}});
 assert(w.eval('debts.length')===0&&d.querySelector('#debt-error').textContent,'رفض الدين بدون اسم المدين');
 d.querySelector('#debt-name').value='مدين اختبار';await w.saveDebt({preventDefault(){}});
 assert(w.eval('debts.length')===0&&d.querySelector('#debt-dialog').open,'رفض الدين بدون أي مبلغ');
 d.querySelector('#debt-amount-USD').value='100.10';d.querySelector('#debt-amount-TRY').value='200';d.querySelector('#debt-amount-SYP').value='3000';d.querySelector('#debt-date').value='2026-08-03';
 d.querySelector('#debt-form').requestSubmit();await wait(()=>!d.querySelector('#debt-dialog').open);
 const debtID=w.eval('debts[0].id');
 assert(w.eval('debts.length')===1&&w.debtTotal('USD')===100.10&&w.debtTotal('TRY')===200&&w.debtTotal('SYP')===3000,'حفظ اسم المدين والمبالغ الثلاثة في دين واحد');
 assert(w.eval('JSON.stringify(["USD","TRY","SYP"].map(c=>totals(records,c)))')===cashBefore,'الديون لا تؤثر في أرصدة الدخل والمصروفات');
 w.openDebt(debtID);d.querySelector('#debt-name').value='مدين معدل';d.querySelector('#debt-amount-USD').value='120.25';d.querySelector('#debt-amount-TRY').value='';d.querySelector('#debt-notes').value='ملاحظة الدين';
 d.querySelector('#debt-form').requestSubmit();await wait(()=>!d.querySelector('#debt-dialog').open);
 assert(w.debtTotal('USD')===120.25&&w.debtTotal('TRY')===0&&w.eval('debts[0].name')==='مدين معدل','تعديل الاسم والمبلغ وإفراغ عملة واحدة');
 assert(w.eval('history.some(h=>h.before?.type==="debt"&&h.before.amounts.USD===100.10)'),'حفظ النسخة السابقة للدين في سجل التعديلات');
 d.querySelector('#debt-search').value='غير موجود';d.querySelector('#debt-search').dispatchEvent(new w.Event('input',{bubbles:true}));
 assert(d.querySelectorAll('.debts-table tbody tr').length===0,'البحث يصفّي الديون');
 d.querySelector('#debt-search').value='ملاحظة';d.querySelector('#debt-search').dispatchEvent(new w.Event('input',{bubbles:true}));
 assert(d.querySelectorAll('.debts-table tbody tr').length===1,'البحث يشمل الملاحظات');
 w.confirm=()=>false;await w.deleteDebt(debtID);assert(w.debtTotal('USD')===120.25,'إلغاء حذف الدين لا يغير البيانات');
 w.confirm=()=>true;await w.deleteDebt(debtID);assert(w.debtTotal('USD')===0&&w.eval('debts.length')===1,'الحذف يستبعد الدين مع بقاء نسخة للاستعادة');
 w.eval('currentRoute="history";render()');assert(Boolean(d.querySelector('[data-debt-restore]')),'استعادة الديون متاحة في السجل');
 await w.restoreDebt(debtID);assert(w.debtTotal('USD')===120.25,'استعادة الدين ترجع المبالغ الأصلية');
 await w.exportBackup();const debtBackup=JSON.parse(w._download.content);w.validateBackup(debtBackup);
 assert(debtBackup.version===3&&debtBackup.debts.length===1,'النسخة الاحتياطية تشمل الديون وسجلها');
 const invalidDebtBackup=JSON.parse(JSON.stringify(debtBackup));invalidDebtBackup.debts[0].amounts.USD=-1;let invalidDebt=false;try{w.validateBackup(invalidDebtBackup);}catch{invalidDebt=true;}assert(invalidDebt,'رفض نسخة احتياطية بدين غير صالح');
 await w.deleteDebt(debtID);await w.importBackup(new w.File([JSON.stringify(debtBackup)],'debts.json',{type:'application/json'}));
 assert(w.debtTotal('USD')===120.25,'استيراد نسخة الديون يعيد القيم المحفوظة');
 const oldBackup={format:'daftar-backup',version:2,settings:w.eval('structuredClone(settings)'),records:[],history:[]};
 await w.importBackup(new w.File([JSON.stringify(oldBackup)],'old-v2.json',{type:'application/json'}));
 assert(w.debtTotal('USD')===120.25,'استيراد نسخة قديمة بدون ديون لا يمس الديون الحالية');
 w.openDebt();d.querySelector('#debt-name').value='عملة واحدة';d.querySelector('#debt-amount-TRY').value='50';d.querySelector('#debt-form').requestSubmit();await wait(()=>!d.querySelector('#debt-dialog').open);
 assert(w.eval('debts.length')===2&&w.debtTotal('TRY')===50,'يمكن إدخال دين بعملة واحدة فقط');
 const debtsBeforeReset=w.eval('JSON.stringify(debts)');
 // Reset controls must never erase records or silently widen their scope.
 w.eval('currentRoute="settings";currentMonth="2026-09";render()');
 assert(Boolean(d.querySelector('[data-reset-open]'))&&Boolean(d.querySelector('[data-download-system]')),'Reset- en systeemdownloadknoppen zichtbaar in beheer');
 const activeBefore=w.eval('records.filter(r=>!r.deletedAt).length'),settingsBefore=w.eval('JSON.stringify(settings)');
 const expensesBefore=w.eval('records.filter(r=>!r.deletedAt&&r.type==="expense").length');
 await w.openResetDialog();d.querySelector('#reset-kind').value='income';w.updateResetPreview();
 d.querySelector('#reset-confirmation').value='wrong';await w.submitReset({preventDefault(){}});
 assert(w.eval('records.filter(r=>!r.deletedAt).length')===activeBefore&&d.querySelector('#reset-error').textContent,'Verkeerd bevestigingswoord weigert reset');
 d.querySelector('#reset-confirmation').value='تصفير';w.confirm=()=>false;await w.submitReset({preventDefault(){}});
 assert(w.eval('records.filter(r=>!r.deletedAt).length')===activeBefore,'Laatste bevestiging annuleren wijzigt niets');
 w.confirm=()=>true;await w.submitReset({preventDefault(){}});
 assert(w.eval('monthlyRecords().filter(r=>r.type==="income").length')===0,'Maandreset zet inkomsten op nul');
 assert(w.eval('records.filter(r=>!r.deletedAt&&r.type==="expense").length')===expensesBefore,'Inkomstenreset behoudt uitgaven');
 assert(w.eval('monthlyRecords("2026-08").some(r=>r.type==="income")'),'Maandreset behoudt oudere maanden');
 const resetID=w.eval('records.find(r=>r.resetId&&r.deletedAt).resetId');
 assert(w.eval('JSON.stringify(settings)')===settingsBefore,'Reset behoudt instellingen en categorieën');
 w.eval('currentRoute="history";render()');assert(Boolean(d.querySelector('[data-restore-reset]')),'Groepsherstel zichtbaar in geschiedenis');
 await w.restoreResetGroup(resetID);
 assert(w.eval('records.filter(r=>!r.deletedAt).length')===activeBefore,'Gehele resetgroep teruggezet');
 await w.openResetDialog();d.querySelector('#reset-kind').value='expense';d.querySelector('#reset-scope').value='all';w.updateResetPreview();d.querySelector('#reset-confirmation').value='تصفير';await w.submitReset({preventDefault(){}});
 assert(w.eval('records.filter(r=>!r.deletedAt&&r.type==="expense").length')===0,'Uitgavenreset over alle perioden werkt');
 const expenseReset=w.eval('records.find(r=>r.resetId&&r.deletedAt&&r.type==="expense").resetId');
 await w.restoreResetGroup(expenseReset);
 await w.openResetDialog();d.querySelector('#reset-scope').value='all';w.updateResetPreview();d.querySelector('#reset-confirmation').value='تصفير';await w.submitReset({preventDefault(){}});
 assert(w.eval('JSON.stringify(debts)')===debtsBeforeReset,'تصفير الحسابات لا يمس الديون');
 assert(w.eval('records.every(r=>r.deletedAt)')&&w.eval('["USD","TRY","SYP"].every(c=>totals(records,c).balance===0&&totals(records,c).income===0&&totals(records,c).expense===0)'),'Volledige reset zet alle drie valuta’s op nul');
 assert(w.eval('records.length')===10&&w.eval('records.find(r=>r.id==="'+photoID+'").photos.length')===1,'Volledige reset behoudt alle regels en foto’s');
 await w.exportBackup();w.validateBackup(JSON.parse(w._download.content));assert(true,'Back-up na reset is geldig en herstelbaar');
 const fullReset=w.eval('records.find(r=>r.resetId&&r.deletedAt).resetId');await w.restoreResetGroup(fullReset);
 assert(w.eval('records.filter(r=>!r.deletedAt).length')===activeBefore,'Volledige reset kan in één keer worden hersteld');
 await w.openResetDialog();d.querySelector('#reset-month').value='2099-01';w.updateResetPreview();assert(d.querySelector('#reset-submit').disabled,'Lege periode heeft geen actieve resetknop');d.querySelector('#reset-dialog').close();
 // Verify the actual compressed ZIP, not just a download notification.
 const archive=await w.DaftarPackage.buildZip();
 const unpacked=w.fflate.unzipSync(archive.bytes);
 assert(archive.bytes[0]===80&&archive.bytes[1]===75&&Object.keys(unpacked).length===archive.fileCount,'ملف ZIP حقيقي ويمكن فك ضغطه');
 assert(w.DaftarPackage.projectFiles.every(path=>unpacked['daftar-project/'+path]),'الأرشيف يحتوي كل ملفات المشروع وملفات الاختبار والترخيص');
 assert(w.fflate.strFromU8(unpacked['daftar-project/index.html']).includes('css/brand-colors.css')&&w.fflate.strFromU8(unpacked['daftar-project/js/debts.js']).includes('function saveDebt'),'ملفات ZIP تشمل الألوان والديون دون فقد وظائف');
 assert(archive.bytes.length<Object.values(unpacked).reduce((sum,bytes)=>sum+bytes.length,0)&&unpacked['daftar-project/START-HERE.txt'],'الأرشيف مضغوط فعلًا ويحتوي تعليمات عربية');
 const archivedApp=w.fflate.strFromU8(unpacked['daftar-project/daftar-system.html']);
 assert(archivedApp.includes('daftar-standalone')&&!archivedApp.includes('دفتر الاختبار'),'ZIP يتضمن نسخة HTML مستقلة بدون بيانات الحسابات الشخصية');
 // Build the actual downloadable file, then run it with all network access blocked.
 const packed=await w.DaftarPackage.build();const packedDoc=new DOMParser().parseFromString(packed,'text/html');
 assert(Boolean(packedDoc.querySelector('meta[name="daftar-standalone"]'))&&!packedDoc.querySelector('script[src],link[rel="stylesheet"]'),'Download bevat alle code en stijlen zonder externe afhankelijkheden');
 assert(!packed.includes('Test inkomen')&&!packed.includes('دفتر الاختبار'),'Systeembestand bevat geen persoonlijke boekingen of instellingen');
 const offline=document.createElement('iframe');offline.title='Offline pakkettest';document.body.append(offline);
 const offlineDB='daftar-package-test-'+Date.now();
 const offlineSetup=`const nativeOpen=indexedDB.open.bind(indexedDB);indexedDB.open=(name,version)=>nativeOpen('${offlineDB}',version);window.fetch=()=>{throw new Error('Network blocked for offline test')};`;
 offline.srcdoc=packed.replace('<head>',`<head><script>${offlineSetup}</script>`);
 await wait(()=>offline.contentDocument.querySelector('.currency-card'));
 const ow=offline.contentWindow,od=offline.contentDocument;
 assert(ow.eval('records.length')===0&&od.querySelectorAll('.currency-card').length===3,'Gedownload HTML-bestand start zonder netwerk en zonder privégegevens');
 ow.applyTheme('light');assert(ow.getComputedStyle(od.querySelector('.primary')).backgroundColor==='rgb(43, 95, 179)','الملف المستقل يتضمن الألوان الجديدة دون اعتماد خارجي');
 ow.openEntry('income');od.querySelector('#income-amount-USD').value='11';od.querySelector('#income-amount-TRY').value='22';od.querySelector('#income-amount-SYP').value='33';od.querySelector('#entry-form').requestSubmit();await wait(()=>!od.querySelector('#entry-dialog').open);
 assert(ow.eval('records.length')===3,'Offline bestand slaat drie valuta’s op');
 ow.eval('currentRoute="settings";render()');
 assert(od.querySelector('[data-reset-open]')&&!od.querySelector('[data-download-system]'),'Zelfstandig bestand heeft reset en correcte kopieerinstructie');
 ow.confirm=()=>true;await ow.openResetDialog();od.querySelector('#reset-confirmation').value='تصفير';await ow.submitReset({preventDefault(){}});
 assert(ow.eval('monthlyRecords().length')===0,'Offline bestand kan rekeningen resetten');
 ow.eval('currentRoute="debts";render()');ow.openDebt();od.querySelector('#debt-name').value='دين دون اتصال';od.querySelector('#debt-amount-USD').value='19.50';od.querySelector('#debt-form').requestSubmit();await wait(()=>!od.querySelector('#debt-dialog').open);
 assert(ow.debtTotal('USD')===19.50&&od.querySelector('.debts-table'),'قسم الديون يعمل في ملف النظام المستقل دون شبكة');
 ow.eval('db.close()');offline.remove();indexedDB.deleteDatabase(offlineDB);
 // Simulate an existing version-1 database and load the actual app to migrate it.
 const migrationDB='daftar-migration-test-'+Date.now();
 const oldDB=await new Promise((resolve,reject)=>{const req=indexedDB.open(migrationDB,1);req.onupgradeneeded=()=>['records','history','settings'].forEach(name=>req.result.createObjectStore(name,{keyPath:'id'}));req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});
 const oldRow={...backup.records[0],id:'preexisting-record'};
 await new Promise((resolve,reject)=>{const tx=oldDB.transaction(['records','settings'],'readwrite');tx.objectStore('records').put(oldRow);tx.objectStore('settings').put(backup.settings);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});oldDB.close();
 const migrated=document.createElement('iframe');document.body.append(migrated);
 const migrationSetup=`const nativeOpen=indexedDB.open.bind(indexedDB);indexedDB.open=(name,version)=>nativeOpen('${migrationDB}',version);`;
 migrated.srcdoc=packed.replace('<head>',`<head><script>${migrationSetup}</script>`);
 await wait(()=>migrated.contentDocument.querySelector('.currency-card'));
 assert(migrated.contentWindow.eval('db.version')===2&&migrated.contentWindow.eval('db.objectStoreNames.contains("debts")'),'ترقية قاعدة البيانات تضيف مخزن الديون');
 assert(migrated.contentWindow.eval('records[0].id')==='preexisting-record'&&migrated.contentWindow.eval('records[0].amount')===oldRow.amount,'الترقية تحفظ العمليات القديمة دون فقدان');
 migrated.contentWindow.eval('db.close()');migrated.remove();indexedDB.deleteDatabase(migrationDB);
 console.log('ALL TESTS PASSED: '+lines.length);output.textContent='ALL TESTS PASSED: '+lines.length+'\n\n'+output.textContent;output.dataset.done='true';
 w.eval('db.close()');indexedDB.deleteDatabase(dbName);
 }catch(error){console.error('TEST FAILED',error.stack);output.textContent='FAIL: '+error.message+'\n\n'+output.textContent;output.dataset.done='failed';indexedDB.deleteDatabase(dbName);}
})();
